version: '3'
services:
  laravel:
    build:
        context: .
        dockerfile: Dockerfile-laravel
    container_name: laravel-broadcast-app-php
    restart: always
    volumes:
        - ./app:/app/app
        - ./public:/app/public
        - ./.env:/app/.env
    environment:
        - DB_CONNECTION=sqlite
        - DB_DATABASE=/app/database/database.sqlite
    ports:
      - "8000:80"
