version: '3'
services:
  laravel:
    build:
        context: .
        dockerfile: Dockerfile-laravel
    container_name: laravel-broadcast-app-php
    restart: always
    volumes:
        - ./app:/app/app
        - ./public:/app/public
        - ./.env:/app/.env
    environment:
        - DB_CONNECTION=sqlite
        - DB_DATABASE=/app/database/database.sqlite
    ports:
      - "8000:80"
  npm:
      build:
          context: .
          dockerfile: Dockerfile-npm
      container_name: laravel-broadcast-app-npm
      volumes:
          - ./resources:/app/resources
          - ./public:/app/public
          - ./.env:/app/.env
          - ./webpack.mix.js:/app/webpack.mix.js
